name: detecting-biased-language
description: 'lint for biased lang'
inputs:
    token:
        description: 'Github Token'
    path:
        description: 'Project Path'
    url:
        description: 'Project URL'
    repo:
        description: 'Project Repo'
runs:
    using: 'composite'
    steps:
        - run: echo $GITHUB_WORKSPACE $GITHUB_SERVER_URL $GITHUB_REPOSITORY
          shell: bash
        # - run: echo "${{inputs.token}}" | docker login ghcr.io -u ${{github.actor}} --password-stdin
        #   shell: bash
        # - run: docker pull ghcr.io/splunk/biased_lang
        #   shell: bash
        # - run: docker run -v ${{inputs.path}}:/biased_lang -e GITHUB_URL=${{inputs.url}} -e GITHUB_REPO=${{inputs.repo}} ghcr.io/splunk/biased_lang
        #   shell: bash
