name: detecting-biased-language
description: 'lint for biased lang'
inputs:
    token:
        description: 'Github Token'
runs:
    using: 'composite'
    steps:
#         - run: echo "${{inputs.token}}" | docker login ghcr.io -u ${{github.actor}} --password-stdin
#           shell: bash
        - run: docker pull ghcr.io/splunk/biased_lang:test
          shell: bash
        - run: docker run -v $GITHUB_WORKSPACE:/biased_lang -e GITHUB_URL=$GITHUB_SERVER_URL -e GITHUB_REPO=$GITHUB_REPOSITORY ghcr.io/splunk/biased_lang:test
          shell: bash
